### ISSUE TITLE
Wrong region code

### ISSUE THREAD

**Issue by Kladdkaka** [ipapi-co/api#1]
hi!

thanks for this api, it looks awesome :)

I just found a little bug (i think), the region code for my ip is this https://ipapi.co/81.234.60.162/json/

in the api it's "AB", which is wrong I believe.

It's not a big deal, and I really don't care about it myself, but I just wanted to point it out, in case you guys are parsing any file wrongly, the "AB" could maybe from the organization?

**Comment by ipapi-co** [comment]
@Kladdkaka Glad you've found the API useful :+1: 

The "AB" region code is the ISO code for subdivision Stockholms län (Stockholm County) (as mentioned here https://en.wikipedia.org/wiki/Counties_of_Sweden). This appears to be correct, so we are closing the issue.
