### ISSUE TITLE
support cors

### ISSUE THREAD

**Issue by jimmywarting** [ipapi-co/api#2]
so we can make ajax request

**Comment by ipapi-co** [comment]
@jimmywarting We support CORS, you can check the [IP Location API examples](https://ipapi.co/api/). If you are facing a specific issue, please feel free to drop us a [message ](https://ipapi.co/contact/). For quick reference, here are 2 examples using jQuery. 

```
$.getJSON('https://ipapi.co/8.8.8.8/json/', function(data){
  console.log(data)
})

```
```
$.ajax({
  url: "https://ipapi.co/json/",
  type: "GET",
  crossDomain: true,
  success: function (resp) {
      console.log(resp);
  },
  error: function (xhr, status) {
      alert("error");
  }
});

```

**Comment by jimmywarting** [comment]
Hmm, you are right.

it was blocked by ublock extension for some reason

**Comment by iorobertob** [comment]
Any word on how to get by this blockage by "ublock"? we dont want our users to have to disable their extension nor change to another one that works.

**Comment by ipapi-co** [comment]
@iorobertob : Can you please drop a message to [customer support](https://ipapi.co/contact) for this.

**Comment by jimmywarting** [comment]
think the reason why it is blocked is due to ip sniffing (collecting data)
there where severals ip-lookup services that where blocked...
