### ISSUE TITLE
Problems in some browsers

### ISSUE THREAD

**Issue by adominguez** [ipapi-co/api#3]
Hi, I'm using your Api to get the user location.

I'm using javascript to get this information like:

```
fetch('https://ipapi.co/json/')
  .then( resp =>  resp.text())
  .then( data => {
  const {country_code: countryCode} = JSON.parse(data)
  fetch(`https://xxxxxxxxxx.com?country=${countryCode}`)
    .then( response=>  response.json() )
    .then((data) => console.log('some code with ', data));
})
```
sometimes it works ok and other times wrong.

Sometimes in Google Chrome I have this error: __Failed to fetch__ --> testint with Chrome 38, Chrome81, Chrome80
Sometimes in Opera I have this error: __Failed to fetch__ --> version Chrome67
Normally in Firefox I have this error: __TypeError: NetworkError when attempting to fetch resource.__ --> version Firefox75

Can you help me please?

Thank you

**Comment by ipapi-co** [comment]
@adominguez Can you please send a support request here : https://ipapi.co/contact/ . We'll be glad to be of assistance.
