### ISSUE TITLE
Getting ratelimmited error message although using free plan and it is the first request.

### ISSUE THREAD

**Issue by programmer2k18** [ipapi-co/api#4]
Tech : PHP
`return file_get_contents('https://ipapi.co/8.8.8.8/json/');`
`"{"error": true, "reason": "RateLimited", "message": "For details, see https://ipapi.co/ratelimited/ "}"`

**Comment by ipapi-co** [comment]
Hi, Please contact [ipapi customer support](https://ipapi.co/contact) to resolve this. We'll be happy to resolve the issue.
